apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: nfsc-provisioner
spec:
  storageClassName: nfsc-storage-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
