apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-psql2
  namespace: psql-dev
spec:
  storageClassName: psql2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
