apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-psql1
  namespace: psql-dev
spec:
  storageClassName: psql1
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  capacity:
   storage: 10Gi
  nfs:
   path: /mnt/kube_file/psql1
   server: 10.10.25.16

